name: Production Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Discord Message Notify
        if: always()
        run: |
          cat <<EOF > ./tmp_pull_request
          ${{ github.event.pull_request.body }}
          EOF
          NUMBERS=$(grep -o '[0-9]*' ./tmp_pull_request)
          discord_output="-----------------------"
          for number in $NUMBERS; do
              pr_data=$(gh pr view $number --json title,body)
              title=$(echo "$pr_data" | jq -r '.title')
              discord_output="$discord_output\n#$number: $title"
          done
          discord_output="$discord_output\n-----------------------\n"
          color=45973
          if [ ${{ job.status }} = "failure" ]; then
            color="15548997"
          fi
          generate_post_data() {
            cat <<EOF
          {
            "content": "**${{ job.status }}** 🚀 PR Merged **hacker-meshi-core** release → master",
            "embeds": [{
              "title": "${{ github.event.pull_request.title }}",
              "description": "${discord_output}",
              "color": "${color}"
            }]
          }
          EOF
          }
          echo "$(generate_post_data)"
          curl -H "Content-Type: application/json" -X POST -d "$(generate_post_data)" ${{ secrets.DISCORD_WEBHOOK }}
        env:
          GH_TOKEN: ${{ github.token }}
