name: Production Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDC


jobs:
  s3ls:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: test file
        run: |
          mkdir -p ~/tmp
          echo "GitHubActions Test" > ~/tmp/test
          exit

      - name: SSH into instance using Session Manager
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" | envsubst > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" | envsubst > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          scp -o ProxyCommand="sh -c 'aws ssm start-session --target %h --document-name AWS-StartSSHSession --region ${{ env.AWS_REGION }}'" \
          -i ~/.ssh/id_rsa ~/tmp/test ec2-user@${{ vars.STG_INSTANCE_ID }}:~/
          ssh -o ProxyCommand="sh -c 'aws ssm start-session --target %h --document-name AWS-StartSSHSession --region ${{ env.AWS_REGION }}'" \
          -i ~/.ssh/id_rsa ec2-user@${{ vars.STG_INSTANCE_ID }} 'ls'
          exit
